In [48]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv('Call_Detail_Report.csv')
df2 = pd.read_csv('All_Data.csv')

C:\Users\mcguy\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (22,23,24,25,26,42,43,47,50,55,56,57,60) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df1 = df1.drop(columns=['Note Taken', 'Appt Set', 'Lead'])
df1

,Contact ID,Contact Name,Address,Phone,Call Result,Date
0,118500,Cynthia Ornelas,"381 Vineyard Dr Richgrove, CA 93261",6614288302,No Contact,02/26/2021 04:56 PM
1,118505,Joseph Coppola,"1420 W Oak Ave Visalia, CA 93291",3237919612,Skipped,02/26/2021 04:49 PM
2,118509,Kaite Silva,"19481 Road 230 Strathmore, CA 93267",5594674662,Skipped,02/26/2021 04:49 PM
3,118503,Glen Conley,"309 N Park St Visalia, CA 93291",5597402329,No Contact,02/26/2021 04:49 PM
4,118511,Donnie Walton,"3540 S Jackie St Visalia, CA 93277",5599707890,Skipped,02/26/2021 04:49 PM
...,...,...,...,...,...,...
11614,100595,Don Scordino,"3534 E Santa Ana Ave Fresno, CA 93726",5594360470,No Answer,01/05/2021 01:19 PM
11615,100592,Richard Anderson,"5090 N Roosevelt Ave #7 Fresno, CA 93704",5106850997,Drop Message,01/05/2021 01:20 PM
11616,100595,Don Scordino,"3534 E Santa Ana Ave Fresno, CA 93726",5592130222,Answering Machine,01/05/2021 01:18 PM
11617,100597,Gita Zamanian,"352 W Barstow Ave Fresno, CA 93704",5593497822,Contact,01/05/2021 01:19 PM
11618,100596,Gregory Coleman,"1522 E Decatur Ave Fresno, CA 93720",5592977375,Bad Number,01/05/2021 01:18 PM

In [4]:
df1['Call Result'] = df1['Call Result'].replace('Contact', 1)
df1['Call Result'] = df1['Call Result'].replace('No Contact', -1)
df1['Call Result'] = df1['Call Result'].replace('Skipped', -1)
df1['Call Result'] = df1['Call Result'].replace('No Answer', -1)
df1['Call Result'] = df1['Call Result'].replace('Disconnected', -1)
df1['Call Result'] = df1['Call Result'].replace('Answering Machine', -1)
df1['Call Result'] = df1['Call Result'].replace('Busy', -1)
df1['Call Result'] = df1['Call Result'].replace('Drop Message', -1)
df1['Call Result'] = df1['Call Result'].replace('Other', -1)
df1['Call Result'] = df1['Call Result'].replace('Bad Number', -1)
df1['Call Result'] = df1['Call Result'].replace('Fax', -1)
df1['Call Result'] = df1['Call Result'].replace('Contact', -1)
df1['Call Result'] = df1['Call Result'].replace('DNC Number', -1)
df1['Call Result'] = df1['Call Result'].replace('Line Error', -1)
df1['Call Result'] = df1['Call Result'].replace('Line Problem', -1)

df1

,Contact ID,Contact Name,Address,Phone,Call Result,Date
0,118500,Cynthia Ornelas,"381 Vineyard Dr Richgrove, CA 93261",6614288302,-1,02/26/2021 04:56 PM
1,118505,Joseph Coppola,"1420 W Oak Ave Visalia, CA 93291",3237919612,-1,02/26/2021 04:49 PM
2,118509,Kaite Silva,"19481 Road 230 Strathmore, CA 93267",5594674662,-1,02/26/2021 04:49 PM
3,118503,Glen Conley,"309 N Park St Visalia, CA 93291",5597402329,-1,02/26/2021 04:49 PM
4,118511,Donnie Walton,"3540 S Jackie St Visalia, CA 93277",5599707890,-1,02/26/2021 04:49 PM
...,...,...,...,...,...,...
11614,100595,Don Scordino,"3534 E Santa Ana Ave Fresno, CA 93726",5594360470,-1,01/05/2021 01:19 PM
11615,100592,Richard Anderson,"5090 N Roosevelt Ave #7 Fresno, CA 93704",5106850997,-1,01/05/2021 01:20 PM
11616,100595,Don Scordino,"3534 E Santa Ana Ave Fresno, CA 93726",5592130222,-1,01/05/2021 01:18 PM
11617,100597,Gita Zamanian,"352 W Barstow Ave Fresno, CA 93704",5593497822,1,01/05/2021 01:19 PM
11618,100596,Gregory Coleman,"1522 E Decatur Ave Fresno, CA 93720",5592977375,-1,01/05/2021 01:18 PM

In [5]:
df2.columns

Index(['First Name', 'Last Name', 'Mailing Address', 'Mailing City',
       'Mailing State', 'Mailing Zip Code', 'Property Address',
       'Property City', 'Property State', 'Property Zip Code', 'County',
       'Phone 1', 'Mobile 1', 'Mobile 2', 'Mobile 3', 'Phone 2', 'Phone 3',
       'Email 1', 'Email 2', 'Email 3', 'Email 4', 'Email 5', 'Email 6',
       'Email 7', 'Email 8', 'Email 9', 'Email 10', 'Birthday', 'Second Name',
       'Listing Status', 'Status Change Date', 'Tax Name', 'List Price',
       'Days On Market', 'List Date', 'MLS ID', 'Property Type', 'Bedrooms',
       'Bathrooms', 'Square Footage', 'Year Built', 'Equity',
       'Last Market Sale Date', 'Last Call Result', 'Last Email Status',
       'Create Date', 'Edit Date', 'Source', 'Original List', 'Call Attempts',
       'Manager', 'Vendor Contact ID', 'Group 1', 'List', 'Action Plan',
       'Last Dial Date', 'Last Dial Time', 'Last Contacted Date',
       'Family Member 1', 'Notes', 'Next Activity', 'Lead ID/Contact ID'],
      dtype='object')

In [6]:
df2['Contact Name'] = df2['First Name'] + " " + df2['Last Name']
df2

,First Name,Last Name,Mailing Address,Mailing City,Mailing State,Mailing Zip Code,Property Address,Property City,Property State,Property Zip Code,...,List,Action Plan,Last Dial Date,Last Dial Time,Last Contacted Date,Family Member 1,Notes,Next Activity,Lead ID/Contact ID,Contact Name
0,Jerry,Blasingame,14 E Danner Ave,Porterville,CA,93257.0,10 W Danner Ave,Porterville,CA,93257.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13150,Jerry Blasingame
1,Janet,Haro,340 W Wren Ave,Visalia,CA,93291.0,30 W Wren Ct,Visalia,CA,93291.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13151,Janet Haro
2,Martin,Ramirez,Po Box 833,Richgrove,CA,93261.0,31 Road 172,Delano,CA,93215.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13152,Martin Ramirez
3,E,Rickert,692 W Kanai Ave,Porterville,CA,93257.0,34 S Villa St,Porterville,CA,93257.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13153,E Rickert
4,Joseph,Strnad,8477 Road 228,Terra Bella,CA,93270.0,35 W Danner Ave,Porterville,CA,93257.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13154,Joseph Strnad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84181,Maria,Lourenco,1717 E Ash Ave,Tulare,CA,93274.0,513 N Welch Dr,Tulare,CA,93274.0,...,Uncalled,NaN,2021-02-09,02:09 PM,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,119378,Maria Lourenco
84182,Rocha,Trust,23787 Road 100,Visalia,CA,93277.0,820 E Merritt Ave,Tulare,CA,93274.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,119379,Rocha Trust
84183,Daniel,Rocha,27387 Road 100,Visalia,CA,93277.0,830 E Merritt Ave,Tulare,CA,93274.0,...,Uncalled,NaN,2021-02-09,02:08 PM,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,119381,Daniel Rocha
84184,Pettey,Pat,265 Flowerfield Ln,La Habra Heights,CA,90631.0,840 E Merritt Ave,Tulare,CA,93274.0,...,Uncalled,NaN,2021-02-09,02:08 PM,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,119382,Pettey Pat
84185,Elaine,Loftis,Po Box 485,Reedley,CA,93654.0,1957 Academy Ave,Tulare,CA,93274.0,...,Uncalled,NaN,NaN,NaN,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,119383,Elaine Loftis

In [8]:
df2[df2['Contact Name'] == 'Cynthia Ornelas']

,First Name,Last Name,Mailing Address,Mailing City,Mailing State,Mailing Zip Code,Property Address,Property City,Property State,Property Zip Code,...,List,Action Plan,Last Dial Date,Last Dial Time,Last Contacted Date,Family Member 1,Notes,Next Activity,Lead ID/Contact ID,Contact Name
83425,Cynthia,Ornelas,12406 Apiary Ct,Bakersfield,CA,93313.0,381 Vineyard Dr,Richgrove,CA,93261.0,...,Uncalled,NaN,2021-02-26,04:56 PM,NaN,NaN,[2021-01-27 10:17 PM] [b]Found owner informati...,NaN,118500,Cynthia Ornelas

In [42]:
df3 = df2.merge(df1)
df3 = df3.drop_duplicates()
df3 = df3[['Contact Name', 'Mailing Address', 'Mailing City', 'Mailing State', 'Mailing Zip Code', 'Property Address',
       'Property City', 'Property State', 'Property Zip Code', 'County','Property Type','Call Attempts','Call Result', 'Date', 'Phone']]

In [43]:
df3.columns

Index(['Contact Name', 'Mailing Address', 'Mailing City', 'Mailing State',
       'Mailing Zip Code', 'Property Address', 'Property City',
       'Property State', 'Property Zip Code', 'County', 'Property Type',
       'Call Attempts', 'Call Result', 'Date', 'Phone'],
      dtype='object')

In [46]:
df3.dropna()
df3['Property Type'].unique()

array(['Sfr', nan, 'Single Family Residential',
       'Quadruplex (4 units, any combination)',
       'Duplex (2 units, any combination)', 'Apartment house (5+ units)',
       'Triplex (3 units, any combination)', 'Mobile Home',
       'Apartments (generic)', 'Mobile Home Park', 'Duplex',
       'Planned Unit Development (PUD Residential)',
       'Mobile Home or Trailer Park', 'Residential-Vacant Land',
       'Mobile home', 'Government-Vacant Land',
       'Governmental/Public Use (General)', 'Pasture, Meadow',
       'Orchard (fruit; nut)', 'Food Packing, Packing Plant',
       'Condominium (Residential)', 'Office Bldg (General)',
       'Residential (General) (Single)', 'Office Bldg (multi-story)',
       'Rural Residence (Agricultural)', 'Waste Land, Marsh, Swamp',
       'Day care, Pre-school (Commercial)', 'Store/Office (mixed use)',
       'Park, Playground, Picnic Area', 'Triplex',
       'Retail Stores (Personal Services, Photography, Travel)',
       'Warehouse (Industrial)', 'Restaurant',
       'Crop, Field Crops, Row Crops (all soil classes)', 'Apartment',
       'Private Preserve, Open Space-Vacant Land (Forest Land, Conservation)',
       'Quadruplex', 'Vineyard (Agricultural)', 'Commercial-Vacant Land',
       'Auto repair, auto parts, Garage',
       'Timberland, Forest, Trees (Agricultural)',
       'Charitable organization', 'Industrial-Vacant Land',
       'Medical Bldg', 'Religious, Church, Worship',
       'Agricultural-Unimproved Vacant Land', 'Commercial (General)',
       'Dormitory, Group Quarters (Residential)',
       'Multi-Family-Vacant Land', 'Agricultural / Rural',
       'Industrial (General)', 'Car wash'], dtype=object)

In [52]:
pd.value_counts(df3['Property Type'])

Sfr                                                                     5485
Single Family Residential                                               2881
Duplex (2 units, any combination)                                        941
Triplex (3 units, any combination)                                       653
Quadruplex (4 units, any combination)                                    276
Condominium (Residential)                                                181
Residential-Vacant Land                                                  171
Apartment house (5+ units)                                               158
Apartments (generic)                                                     156
Orchard (fruit; nut)                                                     113
Warehouse (Industrial)                                                   104
Retail Stores (Personal Services, Photography, Travel)                   104
Duplex                                                                    88
Mobile Home                                                               87
Vineyard (Agricultural)                                                   84
Planned Unit Development (PUD Residential)                                84
Office Bldg (General)                                                     82
Mobile home                                                               78
Pasture, Meadow                                                           76
Rural Residence (Agricultural)                                            64
Crop, Field Crops, Row Crops (all soil classes)                           59
Auto repair, auto parts, Garage                                           52
Apartment                                                                 42
Restaurant                                                                37
Residential (General) (Single)                                            35
Medical Bldg                                                              28
Timberland, Forest, Trees (Agricultural)                                  27
Commercial-Vacant Land                                                    26
Industrial-Vacant Land                                                    24
Quadruplex                                                                23
Triplex                                                                   22
Government-Vacant Land                                                    12
Commercial (General)                                                      11
Day care, Pre-school (Commercial)                                          9
Agricultural / Rural                                                       6
Car wash                                                                   6
Dormitory, Group Quarters (Residential)                                    5
Mobile Home or Trailer Park                                                4
Office Bldg (multi-story)                                                  4
Food Packing, Packing Plant                                                4
Governmental/Public Use (General)                                          4
Park, Playground, Picnic Area                                              4
Waste Land, Marsh, Swamp                                                   4
Mobile Home Park                                                           4
Store/Office (mixed use)                                                   4
Multi-Family-Vacant Land                                                   4
Religious, Church, Worship                                                 4
Agricultural-Unimproved Vacant Land                                        3
Private Preserve, Open Space-Vacant Land (Forest Land, Conservation)       3
Industrial (General)                                                       2
Charitable organization                                                    1
Name: Property Type, dtype: int64